language: node_js
node_js:
  - "0.12.7"

cache:
  directories:
    - node_modules
    - bower_components

# whitelist
branches:
  only:
    - dev

before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install
script: gulp test
